dist: xenial
sudo: false

after_success:
 git clone https://github.com/YuraRodni/TravisCI.git ./repo

  cd repo
  git commit -m "Actions done."
  git push

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master